spring.datasource.url=jdbc:mysql://localhost:3306/coursedb
spring.datasource.username=root
spring.datasource.password=Akhil@5189

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080